services:
  api:
    build: ./api
    container_name: api
    restart: always
    env_file: ./api/.env
    ports:
      - "5000:5000"

  web:
    build: ./web
    container_name: web
    restart: always
    env_file: ./web/.env
    ports:
      - "4000:4000"

volumes:
  pgdata: