'use client'

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { AuthContext, AuthProvider } from "@/contexts/AuthContext";
import { usePathname } from "next/navigation";
import { checkIsPublicRoute } from "@/functions/check-is-public-route";
import PrivateRoute from "@/components/PrivateRoute";
import { useContext } from "react";

const raleway = Raleway({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

// export const metadata: Metadata = {
//   title: "Admin - Cardapiozin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={raleway.className}>
      <body suppressHydrationWarning={true} className="bg-gray text-colortext">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
