version: '3.8'

services:
  cardapiozin.api:
    image: cardapiozin.api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres.zmjhclmqvctjmjlpcscv:snYm6QEiQ3SvJek4@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    ports:
      - "5000:5000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: